"""Public environment setup vocabulary for household launch routes."""

from __future__ import annotations

ENVIRONMENT_SETUP_BASELINE = "baseline"
ENVIRONMENT_SETUP_RELOCATE_LOOSE_OBJECTS = "relocate-loose-objects"
ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS = "relocate-cleanup-related-objects"

ENVIRONMENT_SETUP_OPTIONS = (
    ENVIRONMENT_SETUP_BASELINE,
    ENVIRONMENT_SETUP_RELOCATE_LOOSE_OBJECTS,
    ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS,
)

RELOCATION_SETUP_OPTIONS = (
    ENVIRONMENT_SETUP_RELOCATE_LOOSE_OBJECTS,
    ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS,
)
