"""Reusable map artifact utilities for robot cleanup contracts."""

from roboclaws.maps.base_waypoints import (
    BASE_WAYPOINT_GENERATION_POLICY,
    BASE_WAYPOINT_PURPOSE,
    BaseWaypointBuilder,
    BaseWaypointBuilderConfig,
    BaseWaypointBuildError,
    validate_base_waypoints,
)
from roboclaws.maps.bundle import (
    DEFAULT_COSTMAP_PARAMETERS,
    DEFAULT_COSTMAP_PROFILE_ID,
    DEFAULT_ROBOT_PROFILE,
    DEFAULT_ROBOT_PROFILE_ID,
    NAV2_MAP_BUNDLE_SCHEMA,
    NAV2_MAP_BUNDLE_SNAPSHOT_SCHEMA,
    RUNTIME_COSTMAP_GAPS,
    MapBundleValidation,
    metric_map_bundle_metadata,
    validate_base_metric_map_v1_bundle,
    validate_nav2_map_bundle,
    write_nav2_map_bundle,
    write_nav2_map_bundle_snapshot,
)
from roboclaws.maps.preview import (
    BASE_METRIC_MAP_PREVIEW_ROLE,
    RUNTIME_METRIC_MAP_PREVIEW_ROLE,
    SCENE_RENDER_SOURCE_FAMILY,
    TOPDOWN_SCENE_RENDER_ROLE,
    render_base_metric_map_bundle_preview,
    render_runtime_metric_map_preview,
    visual_role_metadata,
)
from roboclaws.maps.route import SIM_COSTMAP_PLANNER, validate_metric_map_route
from roboclaws.maps.runtime_prior_snapshot import (
    RUNTIME_MAP_PRIOR_SNAPSHOT_SCHEMA,
    materialize_runtime_prior_targets,
    runtime_metric_map_from_prior_artifact,
    runtime_prior_snapshot_from_agibot_navigation_memory,
    runtime_prior_snapshot_from_runtime_metric_map,
)

__all__ = [
    "RUNTIME_MAP_PRIOR_SNAPSHOT_SCHEMA",
    "DEFAULT_COSTMAP_PARAMETERS",
    "DEFAULT_COSTMAP_PROFILE_ID",
    "DEFAULT_ROBOT_PROFILE",
    "DEFAULT_ROBOT_PROFILE_ID",
    "NAV2_MAP_BUNDLE_SCHEMA",
    "NAV2_MAP_BUNDLE_SNAPSHOT_SCHEMA",
    "RUNTIME_COSTMAP_GAPS",
    "SIM_COSTMAP_PLANNER",
    "BASE_WAYPOINT_GENERATION_POLICY",
    "BASE_WAYPOINT_PURPOSE",
    "BASE_METRIC_MAP_PREVIEW_ROLE",
    "RUNTIME_METRIC_MAP_PREVIEW_ROLE",
    "SCENE_RENDER_SOURCE_FAMILY",
    "TOPDOWN_SCENE_RENDER_ROLE",
    "BaseWaypointBuilder",
    "BaseWaypointBuilderConfig",
    "BaseWaypointBuildError",
    "MapBundleValidation",
    "runtime_prior_snapshot_from_agibot_navigation_memory",
    "runtime_prior_snapshot_from_runtime_metric_map",
    "materialize_runtime_prior_targets",
    "metric_map_bundle_metadata",
    "runtime_metric_map_from_prior_artifact",
    "render_base_metric_map_bundle_preview",
    "render_runtime_metric_map_preview",
    "validate_base_metric_map_v1_bundle",
    "validate_base_waypoints",
    "validate_metric_map_route",
    "validate_nav2_map_bundle",
    "write_nav2_map_bundle",
    "write_nav2_map_bundle_snapshot",
    "visual_role_metadata",
]
