"""Environment setup vocabulary shared by launch and household runtimes."""

from __future__ import annotations

ENVIRONMENT_SETUP_BASELINE = "baseline"
ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS = "relocate-cleanup-related-objects"
ENVIRONMENT_SETUP_RELOCATE_EVAL_TARGET_OBJECTS = "relocate-eval-target-objects"

ENVIRONMENT_SETUP_OPTIONS = (
    ENVIRONMENT_SETUP_BASELINE,
    ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS,
    ENVIRONMENT_SETUP_RELOCATE_EVAL_TARGET_OBJECTS,
)

RELOCATION_SETUP_OPTIONS = (
    ENVIRONMENT_SETUP_RELOCATE_CLEANUP_RELATED_OBJECTS,
    ENVIRONMENT_SETUP_RELOCATE_EVAL_TARGET_OBJECTS,
)
