#!/usr/bin/env bash
# Build and run the pinned Codex / Claude Code CLI image.

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/../.." && pwd)"

# shellcheck disable=SC1091
source "${script_dir}/coding_agent_toolchain.env"

dockerfile="${ROBOCLAWS_CODE_AGENT_DOCKERFILE:-Dockerfile.coding-agents}"
image="${ROBOCLAWS_CODE_AGENT_IMAGE}"

usage() {
  cat <<'USAGE' >&2
usage: scripts/dev/coding_agent_docker.sh <command> [args...]

commands:
  build                    Build the pinned coding-agent image.
  ensure                   Build the image only when it is missing locally.
  run <codex|claude> ...   Run a pinned CLI in Docker.
  versions                 Print pinned Codex and Claude Code versions.
  install-wrappers <dir>   Write codex/claude wrapper shims into <dir>.
USAGE
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found in PATH" >&2
    exit 1
  fi
}

build_image() {
  require_docker
  docker build \
    -f "${repo_root}/${dockerfile}" \
    --build-arg "ROBOCLAWS_NODE_IMAGE=${ROBOCLAWS_CODE_AGENT_NODE_IMAGE}" \
    --build-arg "CODEX_NPM_PACKAGE=${ROBOCLAWS_CODEX_NPM_PACKAGE}" \
    --build-arg "CLAUDE_CODE_NPM_PACKAGE=${ROBOCLAWS_CLAUDE_CODE_NPM_PACKAGE}" \
    -t "${image}" \
    "${repo_root}"
}

ensure_image() {
  require_docker
  if ! docker image inspect "${image}" >/dev/null 2>&1; then
    build_image
  fi
}

normalized_skill_names() {
  local raw="${1:-}"
  raw="${raw//,/ }"
  local skill
  for skill in $raw; do
    skill="${skill#skills/}"
    skill="${skill%/}"
    [[ -n "${skill}" ]] && printf '%s\n' "${skill}"
  done
}

prepare_isolated_workspace() {
  local task_name="$1"
  local skills_csv="$2"
  local workspace_dir="${ROBOCLAWS_CODE_AGENT_DOCKER_WORKSPACE:-${repo_root}/.tmp/coding-agent-workspaces/${task_name}}"
  local task_dir="${workspace_dir}/task"

  mkdir -p "${task_dir}" "${workspace_dir}/skills"
  rm -f \
    "${workspace_dir}/AGENTS.md" \
    "${workspace_dir}/CLAUDE.md" \
    "${task_dir}/AGENTS.md" \
    "${task_dir}/CLAUDE.md"

  {
    printf '# Roboclaws Isolated Agent Workspace\n\n'
    printf 'This workspace is generated by `scripts/dev/coding_agent_docker.sh`.\n'
    printf 'Read only the task skill mounted under `../skills/` before using MCP tools.\n\n'
    printf 'Mounted skills:\n'
    local skill
    while IFS= read -r skill; do
      [[ -z "${skill}" ]] && continue
      printf -- '- `../skills/%s/SKILL.md`\n' "${skill}"
    done < <(normalized_skill_names "${skills_csv}")
  } >"${task_dir}/README.md"

  printf '%s\n' "${workspace_dir}"
}

prepare_codex_home_from_host_auth() {
  local host_codex_home="$1"
  local target_codex_home="$2"
  local host_auth="${host_codex_home}/auth.json"
  local host_config="${host_codex_home}/config.toml"
  local host_installation_id="${host_codex_home}/installation_id"

  if [[ ! -f "${host_auth}" ]]; then
    echo "error: host Codex auth not found: ${host_auth}" >&2
    exit 1
  fi

  mkdir -p "${target_codex_home}"
  cp "${host_auth}" "${target_codex_home}/auth.json"
  if [[ -f "${host_installation_id}" ]]; then
    cp "${host_installation_id}" "${target_codex_home}/installation_id"
  fi

  if [[ -f "${host_config}" ]]; then
    HOST_CODEX_CONFIG="${host_config}" \
      TARGET_CODEX_CONFIG="${target_codex_home}/config.toml" \
      python3 - <<'PY'
from __future__ import annotations

import json
import os
import tomllib
from pathlib import Path
from typing import Any


def toml_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    raise TypeError(f"unsupported config value type: {type(value).__name__}")


source = Path(os.environ["HOST_CODEX_CONFIG"])
target = Path(os.environ["TARGET_CODEX_CONFIG"])
data = tomllib.loads(source.read_text(encoding="utf-8"))

lines: list[str] = [
    "# Generated by scripts/dev/coding_agent_docker.sh.",
    "# Keeps host Codex auth/provider settings without host agents, hooks, or skills.",
]
for key in ("model", "model_provider", "model_reasoning_effort", "service_tier"):
    if key in data:
        lines.append(f"{key} = {toml_value(data[key])}")

provider_name = data.get("model_provider")
provider = data.get("model_providers", {}).get(provider_name)
if isinstance(provider_name, str) and isinstance(provider, dict):
    lines.append("")
    lines.append(f"[model_providers.{provider_name}]")
    for key in ("name", "base_url", "wire_api", "env_key"):
        if key in provider:
            lines.append(f"{key} = {toml_value(provider[key])}")

target.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
  else
    rm -f "${target_codex_home}/config.toml"
  fi
}

prepare_empty_codex_skills_dir() {
  local skills_parent="$1"
  mkdir -p "${skills_parent}"
  mktemp -d "${skills_parent}/skills.XXXXXX"
}

pass_env_if_set() {
  local -n out_args="$1"
  local name
  shift
  for name in "$@"; do
    if [[ -n "${!name+x}" ]]; then
      out_args+=(-e "${name}")
    fi
  done
}

run_cli() {
  local binary="${1:-}"
  if [[ -z "${binary}" ]]; then
    usage
    exit 2
  fi
  shift
  case "${binary}" in
    codex|claude)
      ;;
    *)
      echo "error: unsupported pinned CLI '${binary}' (expected codex or claude)" >&2
      exit 2
      ;;
  esac

  ensure_image

  local home_dir="${ROBOCLAWS_CODE_AGENT_DOCKER_HOME:-${repo_root}/.tmp/coding-agent-docker-home}"
  mkdir -p "${home_dir}"

  local cwd="${PWD}"
  local network="${ROBOCLAWS_CODE_AGENT_DOCKER_NETWORK:-host}"
  local user_mode="${ROBOCLAWS_CODE_AGENT_DOCKER_USER:-host}"
  local add_host="${ROBOCLAWS_CODE_AGENT_DOCKER_ADD_HOST:-1}"
  local use_host_codex_auth="${ROBOCLAWS_CODE_AGENT_DOCKER_USE_HOST_CODEX_AUTH:-${ROBOCLAWS_CODE_AGENT_DOCKER_USE_HOST_CODEX_HOME:-0}}"
  local host_codex_home="${ROBOCLAWS_CODE_AGENT_DOCKER_HOST_CODEX_HOME:-${CODEX_HOME:-${HOME}/.codex}}"
  local isolate_workspace="${ROBOCLAWS_CODE_AGENT_DOCKER_ISOLATED_WORKSPACE:-${ROBOCLAWS_CODE_AGENT_DOCKER_ISOLATED_NAV_WORKSPACE:-0}}"
  local task_name="${ROBOCLAWS_CODE_AGENT_DOCKER_TASK:-}"
  local mounted_skills="${ROBOCLAWS_CODE_AGENT_DOCKER_SKILLS:-}"
  if [[ "${ROBOCLAWS_CODE_AGENT_DOCKER_ISOLATED_NAV_WORKSPACE:-0}" == "1" ]]; then
    task_name="${task_name:-ai2thor-nav}"
    mounted_skills="${mounted_skills:-ai2thor-navigator}"
  fi
  task_name="${task_name:-task}"
  local disable_codex_system_skills="${ROBOCLAWS_CODE_AGENT_DOCKER_DISABLE_CODEX_SYSTEM_SKILLS:-${isolate_workspace}}"
  local container_workdir="${cwd}"
  local workspace_mount_args=()

  if [[ "${isolate_workspace}" == "1" ]]; then
    if [[ -z "${mounted_skills}" ]]; then
      echo "error: isolated coding-agent workspace requires ROBOCLAWS_CODE_AGENT_DOCKER_SKILLS" >&2
      exit 1
    fi
    local isolated_workspace
    isolated_workspace="$(prepare_isolated_workspace "${task_name}" "${mounted_skills}")"
    container_workdir="${ROBOCLAWS_CODE_AGENT_DOCKER_CONTAINER_WORKDIR:-/workspace/task}"
    workspace_mount_args=(-v "${isolated_workspace}:/workspace")
    local skill
    while IFS= read -r skill; do
      [[ -z "${skill}" ]] && continue
      if [[ ! -f "${repo_root}/skills/${skill}/SKILL.md" ]]; then
        echo "error: requested skill not found: ${repo_root}/skills/${skill}/SKILL.md" >&2
        exit 1
      fi
      workspace_mount_args+=(
        -v "${repo_root}/skills/${skill}:/workspace/skills/${skill}:ro"
      )
    done < <(normalized_skill_names "${mounted_skills}")
  else
    workspace_mount_args=(-v "${repo_root}:${repo_root}")
  fi

  local docker_args=(run --rm)
  if [[ -t 0 && -t 1 ]]; then
    docker_args+=(-it)
  fi
  if [[ -n "${network}" ]]; then
    docker_args+=(--network "${network}")
  fi
  if [[ "${add_host}" == "1" ]]; then
    docker_args+=(--add-host=host.docker.internal:host-gateway)
  fi
  if [[ "${user_mode}" == "host" ]]; then
    docker_args+=(--user "$(id -u):$(id -g)")
  elif [[ "${user_mode}" != "root" ]]; then
    docker_args+=(--user "${user_mode}")
  fi

  docker_args+=(
    -e "HOME=/home/agent"
    -e "TERM=${TERM:-xterm-256color}"
    -v "${home_dir}:/home/agent"
    -w "${container_workdir}"
    "${workspace_mount_args[@]}"
  )
  if [[ "${use_host_codex_auth}" == "1" ]]; then
    if [[ ! -d "${host_codex_home}" ]]; then
      echo "error: host Codex home not found: ${host_codex_home}" >&2
      exit 1
    fi
    local sanitized_codex_home="${ROBOCLAWS_CODE_AGENT_DOCKER_CODEX_HOME:-${home_dir}/.codex-host-auth}"
    prepare_codex_home_from_host_auth "${host_codex_home}" "${sanitized_codex_home}"
    docker_args+=(
      -e "CODEX_HOME=/home/agent/.codex"
      -v "${sanitized_codex_home}:/home/agent/.codex"
    )
  fi
  if [[ "${binary}" == "codex" && "${disable_codex_system_skills}" == "1" ]]; then
    mkdir -p "${home_dir}/.codex"
    local empty_codex_skills_parent="${ROBOCLAWS_CODE_AGENT_DOCKER_CODEX_SKILLS_PARENT:-${home_dir}/.codex-empty-skills}"
    local empty_codex_skills_dir
    empty_codex_skills_dir="$(prepare_empty_codex_skills_dir "${empty_codex_skills_parent}")"
    docker_args+=(-v "${empty_codex_skills_dir}:/home/agent/.codex/skills:ro")
  fi
  pass_env_if_set docker_args \
    ANTHROPIC_API_KEY \
    ANTHROPIC_BASE_URL \
    ANTHROPIC_AUTH_TOKEN \
    CLAUDE_CODE_SIMPLE \
    CLAUDE_CODE_USE_BEDROCK \
    CLAUDE_CODE_USE_VERTEX \
    OPENAI_API_KEY \
    KIMI_API_KEY \
    MIMO_TP_KEY \
    ROBOCLAWS_CLAUDE_PROVIDER \
    ROBOCLAWS_CLAUDE_MODEL \
    ROBOCLAWS_CODEX_PROVIDER \
    ROBOCLAWS_CODEX_MODEL \
    ROBOCLAWS_CODE_AGENT_PROVIDER \
    ROBOCLAWS_CODE_AGENT_MODEL \
    MODEL

  exec docker "${docker_args[@]}" "${image}" "${binary}" "$@"
}

install_wrappers() {
  local shim_dir="${1:-}"
  if [[ -z "${shim_dir}" ]]; then
    usage
    exit 2
  fi
  mkdir -p "${shim_dir}"

  local binary
  for binary in codex claude; do
    cat >"${shim_dir}/${binary}" <<SHIM
#!/usr/bin/env bash
set -euo pipefail
export ROBOCLAWS_CODE_AGENT_IMAGE=${image@Q}
exec ${repo_root@Q}/scripts/dev/coding_agent_docker.sh run ${binary@Q} "\$@"
SHIM
    chmod +x "${shim_dir}/${binary}"
  done
  echo "${shim_dir}"
}

command="${1:-}"
case "${command}" in
  build)
    build_image
    ;;
  ensure)
    ensure_image
    ;;
  run)
    shift
    run_cli "$@"
    ;;
  versions)
    "${BASH_SOURCE[0]}" run codex --version
    "${BASH_SOURCE[0]}" run claude --version
    ;;
  install-wrappers)
    shift
    install_wrappers "$@"
    ;;
  -h|--help|help|"")
    usage
    ;;
  *)
    echo "error: unknown command '${command}'" >&2
    usage
    exit 2
    ;;
esac
