from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, TypedDict

from roboclaws.household.types import CleanupScenario


class HouseholdRuntimeEvidence(TypedDict):
    python_executable: str
    runtime: dict[str, Any]
    model_stats: dict[str, Any]
    scene_xml: str
    metadata_object_count: int | None
    scenario_source: str
    scene_usd: str
    scene_index: int | None
    object_index: dict[str, Any]
    receptacle_index: dict[str, Any]
    scene_index_diagnostics: dict[str, Any]
    scene_binding_diagnostics: dict[str, Any]
    segmentation: dict[str, Any]
    scene_load: dict[str, Any]
    mapping_gaps: list[dict[str, Any]]
    snapshot_artifacts: list[dict[str, Any]]
    semantic_pose_state: dict[str, Any]
    semantic_pose_view_capture: dict[str, Any]
    robot: dict[str, Any] | None
    robot_import: dict[str, Any]
    requested_generated_mess_count: int | None
    generated_mess_count: int | None
    mess_placement_diagnostics: list[dict[str, Any]]
    placement_diagnostics: list[dict[str, Any]]
    scene_index_artifact: dict[str, Any]


class HouseholdBackendPort(Protocol):
    """Typed backend operations consumed by the household session."""

    scenario: CleanupScenario

    def backend_name(self) -> str: ...
    def supports_visual_snapshots(self) -> bool: ...
    def supports_robot_views(self) -> bool: ...
    def requested_mess_count(self) -> int | None: ...
    def object_locations(self) -> dict[str, str]: ...
    def location_relation(self, object_id: str) -> str: ...
    def scene_index_source(self) -> str: ...
    def scene_index_fixture_pose(self, fixture_id: str) -> list[float] | None: ...
    def planner_scene(self) -> dict[str, Any]: ...
    def planner_task_binding(self, object_id: str, receptacle_id: str) -> dict[str, Any]: ...
    def write_snapshot(self, output_path: Path, *, title: str) -> Path | None: ...
    def write_robot_views(
        self,
        output_dir: Path,
        *,
        label: str,
        focus_object_id: str | None = None,
        focus_receptacle_id: str | None = None,
        camera_yaw_offset_deg: float = 0.0,
        camera_pitch_offset_deg: float = 0.0,
    ) -> dict[str, Any]: ...
    def runtime_evidence(self) -> HouseholdRuntimeEvidence: ...
    def close(self) -> None: ...
    def observe(self) -> dict[str, Any]: ...
    def navigate_to_object(self, object_id: str) -> dict[str, Any]: ...
    def navigate_to_waypoint(self, *, waypoint: dict[str, Any]) -> dict[str, Any]: ...
    def navigate_to_relative_pose(
        self,
        *,
        forward_m: float = 0.0,
        lateral_m: float = 0.0,
        yaw_delta_deg: float = 0.0,
    ) -> dict[str, Any]: ...
    def navigate_to_receptacle(self, receptacle_id: str) -> dict[str, Any]: ...
    def pick(self, object_id: str) -> dict[str, Any]: ...
    def open_receptacle(self, receptacle_id: str) -> dict[str, Any]: ...
    def place(self, receptacle_id: str) -> dict[str, Any]: ...
    def place_inside(self, receptacle_id: str) -> dict[str, Any]: ...
    def close_receptacle(self, receptacle_id: str) -> dict[str, Any]: ...
    def done(self, reason: str = "") -> dict[str, Any]: ...
